package quoridor.backend.managers;

import java.util.ArrayList;

import quoridor.backend.containers.Position;

/**
 * @author Team 4 Men And A Cripple
 * @since 2014-05-03
 *
 * This exists because presumably we would want more than one type of
 * pathfinding. For now there is only shortest path but we may implement
 * others.
 */
public interface Path {

    
    /**
     * Return the generated path.
     * 
     * @return The path generated by the pathfinding algorithm.
     */
    public ArrayList<Position> getPath();
    
}
